ALTER TABLE RISHAL.USER_DETAILS
 DROP PRIMARY KEY CASCADE;

DROP TABLE RISHAL.USER_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE RISHAL.USER_DETAILS
(
  USER_NAME        VARCHAR2(30 BYTE),
  USER_ID          VARCHAR2(15 BYTE)            NOT NULL,
  USER_PASSWORD    VARCHAR2(12 BYTE),
  LAST_LOGIN_TIME  DATE
)

DROP SYNONYM RISHAL.USDT;

CREATE OR REPLACE SYNONYM RISHAL.USDT FOR RISHAL.USER_DETAILS;


ALTER TABLE RISHAL.USER_DETAILS ADD (
  PRIMARY KEY
  (USER_NAME)
  USING INDEX
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);
